# Configuration 3 -> 
## Openai-embedding-large

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/openai_large/all_chunks.csv")

In [3]:
df.head()

,id,text
0,/Users/midhunln/Documents/rag20march_with_eval...,Page 1 of 132 \n \n \nMASTER CIRCULAR \n \nSEB...
1,/Users/midhunln/Documents/rag20march_with_eval...,Securities and Exchange Board of India (Issue ...
2,/Users/midhunln/Documents/rag20march_with_eval...,Page 2 of 132 \n \n4. With the issuance of thi...
3,/Users/midhunln/Documents/rag20march_with_eval...,"suffered thereunder, any right, privilege, obl..."
4,/Users/midhunln/Documents/rag20march_with_eval...,regulations and bidding portal. \n7. All liste...

In [4]:
df["id"][0]

'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_0_0'

In [5]:
df.info

<bound method DataFrame.info of                                                      id  \
0     /Users/midhunln/Documents/rag20march_with_eval...
1     /Users/midhunln/Documents/rag20march_with_eval...
2     /Users/midhunln/Documents/rag20march_with_eval...
3     /Users/midhunln/Documents/rag20march_with_eval...
4     /Users/midhunln/Documents/rag20march_with_eval...
...                                                 ...
1103  /Users/midhunln/Documents/rag20march_with_eval...
1104  /Users/midhunln/Documents/rag20march_with_eval...
1105  /Users/midhunln/Documents/rag20march_with_eval...
1106  /Users/midhunln/Documents/rag20march_with_eval...
1107  /Users/midhunln/Documents/rag20march_with_eval...

                                                   text
0     Page 1 of 132 \n \n \nMASTER CIRCULAR \n \nSEB...
1     Securities and Exchange Board of India (Issue ...
2     Page 2 of 132 \n \n4. With the issuance of thi...
3     suffered thereunder, any right, privilege, obl...
4     regulations and bidding portal. \n7. All liste...
...                                                 ...
1103  Page 26 of 28 \n \nAnnexure -6 \n \nReport by ...
1104  quarter. \n \n5 Total no of exemptions given t...
1105  Page 27 of 28 \n \nAnnexure 7 \nList of rescin...
1106  regarding violations of SEBI (PIT) \nRegulatio...
1107  Page 28 of 28 \n \nS. \nNo. \nDate Number Subj...

[1108 rows x 2 columns]>

In [6]:
df_sampled = df.sample(frac = 0.1)

In [7]:
df_sampled.head()

,id,text
997,/Users/midhunln/Documents/rag20march_with_eval...,Page 242 of 261 \nANNEXURE 22 \n \nFORMAT FOR ...
705,/Users/midhunln/Documents/rag20march_with_eval...,• Conclude on the appropriateness of the Board...
804,/Users/midhunln/Documents/rag20march_with_eval...,Name of authority Brief of the case Correctiv...
207,/Users/midhunln/Documents/rag20march_with_eval...,Page 87 of 132 \n \n \nb. ASBA: Bank Account N...
342,/Users/midhunln/Documents/rag20march_with_eval...,"/ year ended March 31, 2017, the formats were ..."

In [8]:
!pip install langchain-ollama

Requirement already satisfied: langchain-ollama in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (1.0.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-ollama) (1.2.20)
Requirement already satisfied: ollama<1.0.0,>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-ollama) (0.6.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (24.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.14.1)
Requirement already satisfied: httpx>=0.27 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from ollama<1.0.0,>=0.6.0->langchain-ollama) (0.28.1)
Requirement already satisfied: anyio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (4.12.1)
Requirement already satisfied: certifi in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.6.3)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [9]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

chat = ChatOllama(model = "llama3")

/Users/midhunln/Documents/rag20march_with_eval/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [10]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

chat = ChatOllama(model="llama3")

def llm_call(text):
    prompt = f"""
You are a query generator. Based on the text below, generate a concise search query
that a user would likely use to find this information. The output must only have the query and nothing else.
It is very important that the output is only the query and nothing else.

Text:
{text}
"""
    response = chat.invoke([HumanMessage(content=prompt)])
    return response.content.strip()


# Apply row-wise correctly
df_sampled["query"] = df_sampled["text"].apply(llm_call)

In [11]:
df_sampled["query"].iloc[2]

'"public policy positions advocated by entity"'

In [12]:
df_sampled.to_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/openai_large/chunk_to_query_mapping.csv", index = False)

In [13]:
df_sampled.head()

,id,text,query
997,/Users/midhunln/Documents/rag20march_with_eval...,Page 242 of 261 \nANNEXURE 22 \n \nFORMAT FOR ...,"""voting results submission format"""
705,/Users/midhunln/Documents/rag20march_with_eval...,• Conclude on the appropriateness of the Board...,"""auditor's report going concern"""
804,/Users/midhunln/Documents/rag20march_with_eval...,Name of authority Brief of the case Correctiv...,"""public policy positions advocated by entity"""
207,/Users/midhunln/Documents/rag20march_with_eval...,Page 87 of 132 \n \n \nb. ASBA: Bank Account N...,"""Asba application process"""
342,/Users/midhunln/Documents/rag20march_with_eval...,"/ year ended March 31, 2017, the formats were ...","""Companies Act 2013 financial results publicat..."

# Construct the qrels dataset for rankx

In [14]:
qrels = {}

for _, row in df_sampled.iterrows():
    query = row["query"]
    doc_id = row["id"]

    if query not in qrels:
        qrels[query] = {}

    qrels[query][doc_id] = 1  # relevance score

In [15]:
qrels

{'"voting results submission format"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_241_47': 1},
 '"auditor\'s report going concern"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_127_5': 1},
 '"public policy positions advocated by entity"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_172_4': 1},
 '"Asba application process"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_86_7': 1},
 '"Companies Act 2013 financial results publication"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_13_42': 1},
 '"corporate bodies shareholding"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_72_9': 1},
 '"Promoter selling shares"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_35_11': 1},
 '"bank audit opinion"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_121_29': 1},
 '"effectiveness dates of accounting tables"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_8_26': 1},
 '"XYZ & Co. audit report"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_113_43': 1},
 'turnover rate over the past 3 years': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_142_41': 1},
 '"listed entities default loans financial institutions securities"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_27_37': 1},
 '"SEBI application channels for investors"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_28_33': 1},
 '"Protection Fund IEPF"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_72_8': 1},
 '"Public issue application process for retail individual investors"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_105_2': 1},
 '"lodr regulations schedule iii disclosure events"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_213_14': 1},
 '"listed entity suspension trading"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_54_19': 1},
 '"dispute employment termination"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_179_20': 1},
 '"responsible business conduct stakeholder complaints mechanism"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_143_43': 1},
 '"environmental initiatives"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_171_2': 1},
 '"ghg emission intensity measurement data"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_206_47': 1},
 '"auditor\'s responsibilities for consolidated financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_126_47': 1},
 '"guarantee letter loan debt"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_86_37': 1},
 '"Scope 3 emissions calculation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_199_34': 1},
 '"consolidated financial results going concern accounting"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_122_32': 1},
 '"SEBI IPEF payment options"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_7_17': 1},
 '"SEBI code of conduct research analyst regulations"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_43_33': 1},
 '"quarterly financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_99_28': 1,
  '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_120_24': 1},
 '"listed entity information"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_81_26': 1},
 '"complaints workplace"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_160_31': 1},
 '"consolidated financial statements audit procedures"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_94_10': 1},
 '"conflict of interest board members process"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_150_9': 1},
 '"accounting standards auditing financial reporting"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_100_32': 1},
 '"IDR redemption account"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_90_49': 1},
 '"sebi listing obligations disclosure requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_114_45': 1},
 '"water intensity"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_164_38': 1},
 '"accounting policies and internal financial controls"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_126_0': 1},
 '"provisioning by banks + V-D statutory auditors + VI compliance requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_2_11': 1},
 '"Independent committee board director qualifications"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_249_18': 1},
 '"ASBA facility merchant bankers Registrar"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_103_0': 1},
 '"block multiple amounts compensation format"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_101_44': 1},
 '"demat account transactions"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_20_42': 1},
 '"NGRBCs company review"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_146_49': 1},
 '"IDR fungibility rules and regulations"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_90_47': 1},
 '"ASBA process for public and rights issue in India"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_20_2': 1},
 '"listed entity disclosure requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_227_9': 1},
 '"board action plan development"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_251_25': 1},
 '"debt security disclosure guidelines"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_87_39': 1},
 '"Page 92"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_91_17': 1},
 '"auditor procedures for component financial information"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_95_15': 1},
 '"rights issue application form"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_24_18': 1},
 '"SEBI regulations composition board of directors committees"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_80_23': 1},
 '"SEBI insider trading regulations 2015"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_26_6': 1},
 '"uniform listing agreement securities and exchange board of india"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_6_16': 1},
 '"SEBI regulations 2015 LODR"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_11_29': 1},
 '"stock exchange notice Z category non-compliant entity"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_53_13': 1},
 '"e-voting registration options"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_38_19': 1},
 '"awarding of orders contracts terms and conditions"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_223_47': 1},
 '"auditor\'s responsibilities in financial reporting"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_127_2': 1},
 '"VWAP calculation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_236_35': 1},
 '"meeting committee quorum directors"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_79_21': 1},
 '"SEBI ICDR Regulations"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_2_5': 1},
 '"ASBA UPI mock trial run"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_117_20': 1},
 '"WACA calculation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_41_19': 1},

# Start retriever

In [16]:
!pip install langchain-pinecone

Requirement already satisfied: langchain-pinecone in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (0.2.13)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.34 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (1.2.20)
Requirement already satisfied: pinecone<8.0.0,>=6.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (7.3.0)
Requirement already satisfied: numpy!=2.0.2,>=1.26.4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (2.3.1)
Requirement already satisfied: langchain-openai>=0.3.11 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (1.1.11)
Requirement already satisfied: httpx>=0.28.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (0.28.1)
Requirement already satisfied: simsimd>=5.9.11 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (6.5.16)
Requirement already satisfied: pydantic>=2.11.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (2.12.5)
Requirement already satisfied: anyio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (4.12.1)
Requirement already satisfied: certifi in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (1.0.9)
Requirement already satisfied: idna in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.28.0->langchain-pinecone) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (24.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.14.1)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-openai>=0.3.11->langchain-pinecone) (2.29.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-openai>=0.3.11->langchain-pinecone) (0.12.0)
Requirement already satisfied: pinecone-plugin-assistant<2.0.0,>=1.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.8.0)
Requirement already satisfied: pinecone-plugin-interface<0.0.8,>=0.0.7 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.0.7)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.0.post0)
Requirement already satisfied: urllib3>=1.26.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.3)
Requirement already satisfied: aiohttp>=3.9.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (3.13.3)
Requirement already satisfied: aiohttp-retry<3.0.0,>=2.9.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (0.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.23.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.25.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (0.13.0)
Requirement already satisfied: sniffio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (1.3.1)
Requirement already satisfied: tqdm>4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (4.67.3)
Requirement already satisfied: six>=1.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from python-dateutil>=2.5.3->pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.17.0)
Requirement already satisfied: regex>=2022.1.18 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai>=0.3.11->langchain-pinecone) (2026.2.28)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.4.6)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [17]:
import sys
sys.path.append('/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval')

from dotenv import load_dotenv
load_dotenv("/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/ingestion.env")

from Repositories.pinecone_repository import PineconeRepository

In [18]:
from Repositories.pinecone_repository import PineconeConfig
from src.openai_embedding import OpenAIEmbedding
from src.sparse_embedding import SentenceTransformerSparseEmbedding

In [19]:
config = PineconeConfig()

dense_embedding_strategy = OpenAIEmbedding(config)

sparse_embedding_strategy = SentenceTransformerSparseEmbedding(config)

Loading weights: 100%|██████████| 204/204 [00:00<00:00, 31608.35it/s]
The tied weights mapping and config for this model specifies to tie bert.embeddings.word_embeddings.weight to cls.predictions.decoder.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
BertForMaskedLM LOAD REPORT from: naver/splade-cocondenser-ensembledistil
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [20]:
import os

In [21]:
pinecone_repository = PineconeRepository(
            api_key=os.getenv("PINECONE_API_KEY"),
            environment=os.getenv("PINECONE_ENVIRONMENT", "us-east-1-aws"),
            dense_embedding_strategy=dense_embedding_strategy,
            sparse_embedding_strategy=sparse_embedding_strategy,
            pinecone_config=config
        )

In [22]:
df_sampled["relevant_docs"] = df_sampled["query"].apply(pinecone_repository.query_vector_store_for_rankx)

In [23]:
df_sampled.to_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/openai_large/chunk_query_relevant_docs.csv", index = False)

In [24]:
df_sampled.head()

,id,text,query,relevant_docs
997,/Users/midhunln/Documents/rag20march_with_eval...,Page 242 of 261 \nANNEXURE 22 \n \nFORMAT FOR ...,"""voting results submission format""",[{'id': '/Users/midhunln/Documents/rag20march_...
705,/Users/midhunln/Documents/rag20march_with_eval...,• Conclude on the appropriateness of the Board...,"""auditor's report going concern""",[{'id': '/Users/midhunln/Documents/rag20march_...
804,/Users/midhunln/Documents/rag20march_with_eval...,Name of authority Brief of the case Correctiv...,"""public policy positions advocated by entity""",[{'id': '/Users/midhunln/Documents/rag20march_...
207,/Users/midhunln/Documents/rag20march_with_eval...,Page 87 of 132 \n \n \nb. ASBA: Bank Account N...,"""Asba application process""",[{'id': '/Users/midhunln/Documents/rag20march_...
342,/Users/midhunln/Documents/rag20march_with_eval...,"/ year ended March 31, 2017, the formats were ...","""Companies Act 2013 financial results publicat...",[{'id': '/Users/midhunln/Documents/rag20march_...

In [25]:
df_sampled["relevant_docs"].iloc[0]

[{'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_37_17',
  'score': 25.9270592},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_241_47',
  'score': 20.3109837},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_60_35',
  'score': 19.9712582},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_13_39',
  'score': 16.5698128},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_2_11',
  'score': 16.4527149},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_59_33',
  'score': 13.8990078},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_50_1',
  'score': 13.7453251},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_14_44',
  'score': 12.9103403},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_16_2',
  'score': 12.8540697},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_13_38',
  'score': 12.6125507}]

In [26]:
qrels_dict = {}

for i, row in df_sampled.iterrows():
    qid = str(i)
    true_doc = row["id"]   # single doc id string
    qrels_dict[qid] = {true_doc: 1}

In [27]:
run_dict = {}

for i, row in df_sampled.iterrows():
    qid = str(i)
    
    run_dict[qid] = {
        doc["id"]: float(doc["score"])
        for doc in row["relevant_docs"]
    }

In [28]:
from ranx import Qrels, Run, evaluate

qrels = Qrels(qrels_dict)
run = Run(run_dict)

metrics = [
    "mrr",
    "ndcg@10",
    "recall@5",
    "recall@10",
    "precision@5"
]

results = evaluate(qrels, run, metrics)
print(results)

{'mrr': np.float64(0.601176176176176), 'ndcg@10': np.float64(0.6547493420526447), 'recall@5': np.float64(0.7567567567567568), 'recall@10': np.float64(0.8198198198198198), 'precision@5': np.float64(0.1513513513513513)}

In [29]:
final_result = pd.Series(results)

In [32]:
result = pd.Series(results)

In [33]:
result

mrr            0.601176
ndcg@10        0.654749
recall@5       0.756757
recall@10      0.819820
precision@5    0.151351
dtype: float64