# Configuration 2 -> 
## Openai-embedding-small

In [57]:
import pandas as pd

In [58]:
df = pd.read_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/openai_small/all_chunks.csv")

In [59]:
df.head()

,id,text
0,/Users/midhunln/Documents/rag20march_with_eval...,Page 1 of 132 \n \n \nMASTER CIRCULAR \n \nSEB...
1,/Users/midhunln/Documents/rag20march_with_eval...,Securities and Exchange Board of India (Issue ...
2,/Users/midhunln/Documents/rag20march_with_eval...,Page 2 of 132 \n \n4. With the issuance of thi...
3,/Users/midhunln/Documents/rag20march_with_eval...,"suffered thereunder, any right, privilege, obl..."
4,/Users/midhunln/Documents/rag20march_with_eval...,regulations and bidding portal. \n7. All liste...

In [60]:
df["id"][0]

'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_0_0'

In [61]:
df.info

<bound method DataFrame.info of                                                      id  \
0     /Users/midhunln/Documents/rag20march_with_eval...
1     /Users/midhunln/Documents/rag20march_with_eval...
2     /Users/midhunln/Documents/rag20march_with_eval...
3     /Users/midhunln/Documents/rag20march_with_eval...
4     /Users/midhunln/Documents/rag20march_with_eval...
...                                                 ...
1103  /Users/midhunln/Documents/rag20march_with_eval...
1104  /Users/midhunln/Documents/rag20march_with_eval...
1105  /Users/midhunln/Documents/rag20march_with_eval...
1106  /Users/midhunln/Documents/rag20march_with_eval...
1107  /Users/midhunln/Documents/rag20march_with_eval...

                                                   text
0     Page 1 of 132 \n \n \nMASTER CIRCULAR \n \nSEB...
1     Securities and Exchange Board of India (Issue ...
2     Page 2 of 132 \n \n4. With the issuance of thi...
3     suffered thereunder, any right, privilege, obl...
4     regulations and bidding portal. \n7. All liste...
...                                                 ...
1103  Page 26 of 28 \n \nAnnexure -6 \n \nReport by ...
1104  quarter. \n \n5 Total no of exemptions given t...
1105  Page 27 of 28 \n \nAnnexure 7 \nList of rescin...
1106  regarding violations of SEBI (PIT) \nRegulatio...
1107  Page 28 of 28 \n \nS. \nNo. \nDate Number Subj...

[1108 rows x 2 columns]>

In [62]:
df_sampled = df.sample(frac = 0.1)

In [63]:
df_sampled.head()

,id,text
886,/Users/midhunln/Documents/rag20march_with_eval...,Page 201 of 261 \n \nthat could adversely affe...
535,/Users/midhunln/Documents/rag20march_with_eval...,20(3) \nDisclosure of the Secretarial Audit R...
214,/Users/midhunln/Documents/rag20march_with_eval...,b. Attention of investors to be drawn to instr...
588,/Users/midhunln/Documents/rag20march_with_eval...,comprehensive income / loss of its associates ...
56,/Users/midhunln/Documents/rag20march_with_eval...,with any other SEBI registered SCSBs. Such acc...

In [64]:
!pip install langchain-ollama

Requirement already satisfied: langchain-ollama in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (1.0.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-ollama) (1.2.20)
Requirement already satisfied: ollama<1.0.0,>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-ollama) (0.6.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (24.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.14.1)
Requirement already satisfied: httpx>=0.27 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from ollama<1.0.0,>=0.6.0->langchain-ollama) (0.28.1)
Requirement already satisfied: anyio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (4.12.1)
Requirement already satisfied: certifi in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.6.3)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [65]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

chat = ChatOllama(model = "llama3")

In [66]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

chat = ChatOllama(model="llama3")

def llm_call(text):
    prompt = f"""
You are a query generator. Based on the text below, generate a concise search query
that a user would likely use to find this information. The output must only have the query and nothing else.
It is very important that the output is only the query and nothing else.

Text:
{text}
"""
    response = chat.invoke([HumanMessage(content=prompt)])
    return response.content.strip()


# Apply row-wise correctly
df_sampled["query"] = df_sampled["text"].apply(llm_call)

In [67]:
df_sampled["query"].iloc[2]

'"issue structure for different investor categories"'

In [68]:
df_sampled.to_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/openai_small/chunk_to_query_mapping.csv", index = False)

In [69]:
df_sampled.head()

,id,text,query
886,/Users/midhunln/Documents/rag20march_with_eval...,Page 201 of 261 \n \nthat could adversely affe...,long term ecological damage habitat sustainabi...
535,/Users/midhunln/Documents/rag20march_with_eval...,20(3) \nDisclosure of the Secretarial Audit R...,"""corporate governance report disclosure"""
214,/Users/midhunln/Documents/rag20march_with_eval...,b. Attention of investors to be drawn to instr...,"""issue structure for different investor catego..."
588,/Users/midhunln/Documents/rag20march_with_eval...,comprehensive income / loss of its associates ...,"""comprehensive income loss associates joint ve..."
56,/Users/midhunln/Documents/rag20march_with_eval...,with any other SEBI registered SCSBs. Such acc...,"""SEBI SCSB ASBA regulations"""

# Construct the qrels dataset for rankx

In [70]:
qrels = {}

for _, row in df_sampled.iterrows():
    query = row["query"]
    doc_id = row["id"]

    if query not in qrels:
        qrels[query] = {}

    qrels[query][doc_id] = 1  # relevance score

In [71]:
qrels

{'long term ecological damage habitat sustainability': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_200_36': 1},
 '"corporate governance report disclosure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_85_35': 1},
 '"issue structure for different investor categories"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_88_14': 1},
 '"comprehensive income loss associates joint ventures quarterly financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_102_38': 1},
 '"SEBI SCSB ASBA regulations"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_21_6': 1},
 '"SEBI UPI payment mechanism for public issue applications"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_29_36': 1},
 '"audit report annual financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_114_46': 1},
 '"SEBI LODR Regulations Guidance Note"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_40_27': 1},
 '"SEBI listing obligations and disclosure requirements regulations"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_259_48': 1},
 '"commodity risk disclosure listed entities"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_253_30': 1},
 '"health and safety training"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_188_48': 1},
 '"company buyback details"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_70_24': 1},
 '"number of complaints filed by employees"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_160_31': 1},
 '"Board of Directors financial reporting responsibilities"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_110_25': 1},
 '"Public Issue ASBA UPI listing timeline"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_2_7': 1},
 '"stock exchange bidding process"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_106_5': 1},
 '"SEBI guidelines for listed entities"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_258_46': 1},
 '"SEBI circulars"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_129_43': 1},
 '"LODR regulations secretarial compliance report"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_21_19': 1},
 '"Environmental protection act compliance water withdrawal"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_169_48': 1},
 '"SEBI Prohibition of Insider Trading Regulations 2015 Annexure 1 Disclosure KMP Director Promoter"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_12_25': 1},
 '"trading window closure period"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_22_48': 1},
 '"foreign investors"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_69_4': 1},
 '"SEBI Master Circular Annexures"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_59_32': 1},
 '"social impact assessment mitigation csr projects procurement marginalized groups"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_174_7': 1},
 '"financial year training awareness programmes directors KMPs employees workers fines penalties settlement amount"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_147_2': 1},
 '"trading window closure period for securities"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_10_22': 1},
 '"sustainable sourcing"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_186_39': 1},
 '"loans investments securities transactions reporting requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_17_5': 1},
 '"Indian labor laws wages sexual harassment discrimination"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_193_13': 1},
 'total waste generated per rupee': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_209_5': 1},
 '"share allotment ratio"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_52_43': 1},
 '"convert IDR to equity"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_89_45': 1},
 '"employee well-being"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_188_46': 1},
 '"UPI PIN confirmation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_109_9': 1},
 '"stock exchange electronic bidding system"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_98_35': 1},
 '"unmodified opinion on audited quarterly financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_114_44': 1},
 '"unaffected price lodr regulations market rumour"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_237_39': 1},
 '"rescinded circulars"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_1_3': 1},
 '"SEBI listing obligations disclosure requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_117_11': 1},
 '"loans guarantees securities financial reporting"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_86_36': 1},
 '"corporate governance compliance report"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_81_25': 1},
 '"structure of securities issuance"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_215_20': 1},
 '"corporate insolvency resolution process CIRP"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_230_18': 1},
 '"SEBI compensation for investor complaints"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_99_40': 1},
 '"corporate governance compliance certificate"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_247_11': 1},
 '"equity investment risk"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_42_21': 1},
 '"auditor communication with governance"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_128_8': 1},
 '"details of means of finance"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_45_28': 1},
 '"counterparty agreements listed entity counterparties"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_219_35': 1},
 '"ASBA application form instructions"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_86_8': 1},
 '"ASBA IPO compensation refund"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_14_35': 1},
 '"modified opinion audit qualifications statement impact"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_16_1': 1},
 '"committee member qualifications"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_249_18': 1},
 '"related party transactions reporting period"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_132_19': 1},
 '"Company transparency community grievances job creation wages paid small towns MSMEs suppliers"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_173_6': 1},
 '"board of directors responsibilities and best practices"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_248_15': 1},
 '"ISD for qualified institutions placement"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_61_9': 1},
 '"ASBA bidding process timelines"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_95_23': 1},
 '"principle 1 business ethics training"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_147_1': 1},
 '"Committee composition and board meeting"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_79_20': 1},
 '"consolidated financial statements audit ICAI"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_103_47': 1},
 '"listed entity disclosure requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_227_9': 1},
 '"SEBI ASBA mechanism payment calls"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_27_30': 1},
 '"financial statement review"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_113_41': 1},
 '"ind as accounting policies footnote"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_92_4': 1},
 '"auditor responsibilities in financial reporting"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_95_16': 1},

# Start retriever

In [72]:
!pip install langchain-pinecone

Requirement already satisfied: langchain-pinecone in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (0.2.13)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.34 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (1.2.20)
Requirement already satisfied: pinecone<8.0.0,>=6.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (7.3.0)
Requirement already satisfied: numpy!=2.0.2,>=1.26.4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (2.3.1)
Requirement already satisfied: langchain-openai>=0.3.11 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (1.1.11)
Requirement already satisfied: httpx>=0.28.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (0.28.1)
Requirement already satisfied: simsimd>=5.9.11 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (6.5.16)
Requirement already satisfied: pydantic>=2.11.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (2.12.5)
Requirement already satisfied: anyio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (4.12.1)
Requirement already satisfied: certifi in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (1.0.9)
Requirement already satisfied: idna in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.28.0->langchain-pinecone) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (24.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.14.1)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-openai>=0.3.11->langchain-pinecone) (2.29.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-openai>=0.3.11->langchain-pinecone) (0.12.0)
Requirement already satisfied: pinecone-plugin-assistant<2.0.0,>=1.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.8.0)
Requirement already satisfied: pinecone-plugin-interface<0.0.8,>=0.0.7 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.0.7)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.0.post0)
Requirement already satisfied: urllib3>=1.26.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.3)
Requirement already satisfied: aiohttp>=3.9.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (3.13.3)
Requirement already satisfied: aiohttp-retry<3.0.0,>=2.9.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (0.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.23.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.25.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (0.13.0)
Requirement already satisfied: sniffio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (1.3.1)
Requirement already satisfied: tqdm>4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (4.67.3)
Requirement already satisfied: six>=1.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from python-dateutil>=2.5.3->pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.17.0)
Requirement already satisfied: regex>=2022.1.18 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai>=0.3.11->langchain-pinecone) (2026.2.28)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.4.6)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [73]:
import sys
sys.path.append('/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval')

from dotenv import load_dotenv
load_dotenv("/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/ingestion.env")

from Repositories.pinecone_repository import PineconeRepository

In [74]:
from Repositories.pinecone_repository import PineconeConfig
from src.openai_embedding import OpenAIEmbedding
from src.sparse_embedding import SentenceTransformerSparseEmbedding

In [75]:
config = PineconeConfig()

dense_embedding_strategy = OpenAIEmbedding(config)

sparse_embedding_strategy = SentenceTransformerSparseEmbedding(config)

Loading weights: 100%|██████████| 204/204 [00:00<00:00, 31985.27it/s]
The tied weights mapping and config for this model specifies to tie bert.embeddings.word_embeddings.weight to cls.predictions.decoder.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
BertForMaskedLM LOAD REPORT from: naver/splade-cocondenser-ensembledistil
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [76]:
import os

In [77]:
pinecone_repository = PineconeRepository(
            api_key=os.getenv("PINECONE_API_KEY"),
            environment=os.getenv("PINECONE_ENVIRONMENT", "us-east-1-aws"),
            dense_embedding_strategy=dense_embedding_strategy,
            sparse_embedding_strategy=sparse_embedding_strategy,
            pinecone_config=config
        )

In [78]:
df_sampled["relevant_docs"] = df_sampled["query"].apply(pinecone_repository.query_vector_store_for_rankx)

In [79]:
df_sampled.to_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/openai_small/chunk_to_query_relevantdocs_mapping.csv", index = False)

In [80]:
df_sampled.head()

,id,text,query,relevant_docs
886,/Users/midhunln/Documents/rag20march_with_eval...,Page 201 of 261 \n \nthat could adversely affe...,long term ecological damage habitat sustainabi...,[{'id': '/Users/midhunln/Documents/rag20march_...
535,/Users/midhunln/Documents/rag20march_with_eval...,20(3) \nDisclosure of the Secretarial Audit R...,"""corporate governance report disclosure""",[{'id': '/Users/midhunln/Documents/rag20march_...
214,/Users/midhunln/Documents/rag20march_with_eval...,b. Attention of investors to be drawn to instr...,"""issue structure for different investor catego...",[{'id': '/Users/midhunln/Documents/rag20march_...
588,/Users/midhunln/Documents/rag20march_with_eval...,comprehensive income / loss of its associates ...,"""comprehensive income loss associates joint ve...",[{'id': '/Users/midhunln/Documents/rag20march_...
56,/Users/midhunln/Documents/rag20march_with_eval...,with any other SEBI registered SCSBs. Such acc...,"""SEBI SCSB ASBA regulations""",[{'id': '/Users/midhunln/Documents/rag20march_...

In [81]:
df_sampled["relevant_docs"].iloc[0]

[{'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_200_36',
  'score': 16.9695168},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_182_30',
  'score': 11.1270905},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_151_10',
  'score': 10.9569683},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_183_34',
  'score': 10.6633291},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_183_33',
  'score': 10.6212416},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_186_41',
  'score': 9.82130146},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_186_39',
  'score': 9.80067635},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_22_21',
  'score': 9.7641058},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_22_23',
  'score': 8.89292526},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_184_36',
  'score': 7.1680603}]

In [82]:
qrels_dict = {}

for i, row in df_sampled.iterrows():
    qid = str(i)
    true_doc = row["id"]   # single doc id string
    qrels_dict[qid] = {true_doc: 1}

In [83]:
run_dict = {}

for i, row in df_sampled.iterrows():
    qid = str(i)
    
    run_dict[qid] = {
        doc["id"]: float(doc["score"])
        for doc in row["relevant_docs"]
    }

In [84]:
from ranx import Qrels, Run, evaluate

qrels = Qrels(qrels_dict)
run = Run(run_dict)

metrics = [
    "mrr",
    "ndcg@10",
    "recall@5",
    "recall@10",
    "precision@5"
]

results = evaluate(qrels, run, metrics)
print(results)

{'mrr': np.float64(0.6157979407979408), 'ndcg@10': np.float64(0.6932942555188456), 'recall@5': np.float64(0.8378378378378378), 'recall@10': np.float64(0.9369369369369369), 'precision@5': np.float64(0.16756756756756752)}

In [85]:
final_result = pd.Series(results)

In [86]:
final_result

mrr            0.615798
ndcg@10        0.693294
recall@5       0.837838
recall@10      0.936937
precision@5    0.167568
dtype: float64

In [87]:
result = pd.Series(results)
result

mrr            0.615798
ndcg@10        0.693294
recall@5       0.837838
recall@10      0.936937
precision@5    0.167568
dtype: float64