# Configuration 1 -> 
## Sentence transformer embedding model

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/sentence_transformers/all_chunks.csv")

In [5]:
df.head()

,id,text
0,/Users/midhunln/Documents/rag20march_with_eval...,Page 1 of 132 \n \n \nMASTER CIRCULAR \n \nSEB...
1,/Users/midhunln/Documents/rag20march_with_eval...,Securities and Exchange Board of India (Issue ...
2,/Users/midhunln/Documents/rag20march_with_eval...,Page 2 of 132 \n \n4. With the issuance of thi...
3,/Users/midhunln/Documents/rag20march_with_eval...,"suffered thereunder, any right, privilege, obl..."
4,/Users/midhunln/Documents/rag20march_with_eval...,regulations and bidding portal. \n7. All liste...

In [6]:
df["id"][0]

'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_0_0'

In [7]:
df.info

<bound method DataFrame.info of                                                      id  \
0     /Users/midhunln/Documents/rag20march_with_eval...
1     /Users/midhunln/Documents/rag20march_with_eval...
2     /Users/midhunln/Documents/rag20march_with_eval...
3     /Users/midhunln/Documents/rag20march_with_eval...
4     /Users/midhunln/Documents/rag20march_with_eval...
...                                                 ...
1103  /Users/midhunln/Documents/rag20march_with_eval...
1104  /Users/midhunln/Documents/rag20march_with_eval...
1105  /Users/midhunln/Documents/rag20march_with_eval...
1106  /Users/midhunln/Documents/rag20march_with_eval...
1107  /Users/midhunln/Documents/rag20march_with_eval...

                                                   text
0     Page 1 of 132 \n \n \nMASTER CIRCULAR \n \nSEB...
1     Securities and Exchange Board of India (Issue ...
2     Page 2 of 132 \n \n4. With the issuance of thi...
3     suffered thereunder, any right, privilege, obl...
4     regulations and bidding portal. \n7. All liste...
...                                                 ...
1103  Page 26 of 28 \n \nAnnexure -6 \n \nReport by ...
1104  quarter. \n \n5 Total no of exemptions given t...
1105  Page 27 of 28 \n \nAnnexure 7 \nList of rescin...
1106  regarding violations of SEBI (PIT) \nRegulatio...
1107  Page 28 of 28 \n \nS. \nNo. \nDate Number Subj...

[1108 rows x 2 columns]>

In [8]:
df_sampled = df.sample(frac = 0.1)

In [9]:
df_sampled.head()

,id,text
35,/Users/midhunln/Documents/rag20march_with_eval...,Page 15 of 132 \n \nChapter 5: Compensation to...
268,/Users/midhunln/Documents/rag20march_with_eval...,Page 117 of 132
643,/Users/midhunln/Documents/rag20march_with_eval...,"income recognition, asset classification, prov..."
377,/Users/midhunln/Documents/rag20march_with_eval...,2026 – 27 Top 1000 listed entities \n \n3. ESG...
478,/Users/midhunln/Documents/rag20march_with_eval...,requirements which is not specified by SEBI un...

In [10]:
!pip install langchain-ollama

Requirement already satisfied: langchain-ollama in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (1.0.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-ollama) (1.2.20)
Requirement already satisfied: ollama<1.0.0,>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-ollama) (0.6.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (24.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.14.1)
Requirement already satisfied: httpx>=0.27 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from ollama<1.0.0,>=0.6.0->langchain-ollama) (0.28.1)
Requirement already satisfied: anyio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (4.12.1)
Requirement already satisfied: certifi in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.6.3)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [11]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

chat = ChatOllama(model = "llama3")

/Users/midhunln/Documents/rag20march_with_eval/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [12]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

chat = ChatOllama(model="llama3")

def llm_call(text):
    prompt = f"""
You are a query generator. Based on the text below, generate a concise search query
that a user would likely use to find this information. The output must only have the query and nothing else.
It is very important that the output is only the query and nothing else.

Text:
{text}
"""
    response = chat.invoke([HumanMessage(content=prompt)])
    return response.content.strip()


# Apply row-wise correctly
df_sampled["query"] = df_sampled["text"].apply(llm_call)

In [13]:
df_sampled["query"].iloc[2]

'"chartered accountants report"'

In [14]:
df_sampled.to_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/sentence_transformers/chunk_to_query_mapping.csv", index = False)

In [15]:
df_sampled.head()

,id,text,query
35,/Users/midhunln/Documents/rag20march_with_eval...,Page 15 of 132 \n \nChapter 5: Compensation to...,"""IPO allotment failure compensation"""
268,/Users/midhunln/Documents/rag20march_with_eval...,Page 117 of 132,"""page 117"""
643,/Users/midhunln/Documents/rag20march_with_eval...,"income recognition, asset classification, prov...","""chartered accountants report"""
377,/Users/midhunln/Documents/rag20march_with_eval...,2026 – 27 Top 1000 listed entities \n \n3. ESG...,"""ESG disclosures value chain"""
478,/Users/midhunln/Documents/rag20march_with_eval...,requirements which is not specified by SEBI un...,"""SEBI circular requirements"""

# Construct the qrels dataset for rankx

In [16]:
qrels = {}

for _, row in df_sampled.iterrows():
    query = row["query"]
    doc_id = row["id"]

    if query not in qrels:
        qrels[query] = {}

    qrels[query][doc_id] = 1  # relevance score

In [17]:
qrels

{'"IPO allotment failure compensation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_14_35': 1},
 '"page 117"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_116_18': 1},
 '"chartered accountants report"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_113_43': 1},
 '"ESG disclosures value chain"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_23_27': 1},
 '"SEBI circular requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_57_28': 1},
 '"Disclosure guidelines for materiality events"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_232_22': 1},
 '"internal control audit procedures going concern basis"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_122_35': 1},
 '"SEBI NCD regulations 2021"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_16_41': 1},
 '"In principle approval stage isd preferential issue securities"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_59_6': 1},
 '"related party transactions disclosure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_17_3': 1},
 '"listed entities commodity risk disclosures"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_41_28': 1},
 '"SEBI ASBA circular"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_22_11': 1},
 '"page 93"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_92_18': 1},
 '"Bank audit findings"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_123_38': 1},
 '"SEBI relaxations COVID-19 pandemic"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_257_41': 1},
 '"Board of Directors members"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_44_27': 1},
 '"auditor\'s report requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_240_45': 1},
 '"stock exchange updates"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_19_41': 1},
 '"stock exchange file format"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_97_34': 1},
 '"SEBI industry standards market rumors verification"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_260_0': 1},
 '"ISD public issue securities"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_56_1': 1},
 '"SEBI master circular securities market regulation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_1_5': 1},
 '"derivative trading company connected persons"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_16_35': 1},
 '"Bank quarterly financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_120_24': 1},
 '"delisting of listed entity"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_53_11': 1},
 '"ICDR Regulations Master Circular rescinded"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_1_2': 1},
 '"corporate governance transparency accounting shareholder empowerment"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_18_10': 1},
 '"Chairperson evaluation criteria"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_250_21': 1},
 '"Principle Wise Performance Disclosure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_147_1': 1},
 '"Consolidated unaudited financial results subsidiaries associates"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_118_16': 1},
 '"listed entity ownership rules"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_9_28': 1},
 '"recycled materials reporting guidelines"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_152_13': 1},
 '"compliance report observations"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_137_30': 1},
 '"SEBI Circular"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_26_27': 1},
 '"ASBA bidding process"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_98_36': 1},
 '"SEBI ICDR Regulations non-compliance fines"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_5_15': 1},
 '"IDR holding pattern"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_88_40': 1},
 '"SEBI circulars COVID-19 pandemic"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_258_45': 1},
 '"SEBI circulars IPOs UPI ASBA investor grievances"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_131_0': 1},
 '"sebi master circular surveillance securities market"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_0_1': 1},
 '"greenhouse gas emissions disclosure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_196_25': 1},
 '"SCSB processing fee application form"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_99_38': 1},
 '"listed entity disclosure requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_221_43': 1},
 '"company compliance report"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_82_28': 1},
 '"audit risks material misstatement"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_107_11': 1},
 '"e-voting authentication process"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_38_21': 1},
 '"ASBA facility responsibilities SCSB"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_96_27': 1},
 '"NGRBCs company policies compliance principles"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_146_49': 1},
 '"electronic bidding system ASBA UPI 2.0 NPCI SCSB"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_80_42': 1},
 '"LODR Regulations relaxation compliance"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_46_39': 1},
 '"ASBA confirmation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_86_7': 1},
 '"quarterly financial results 2019"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_15_49': 1},
 '"shareholders concert details"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_73_10': 1},
 '"ipo procedure in india"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_63_13': 1},
 '"greenhouse gas protocol corporate accounting and reporting standard"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_205_45': 1},
 '"SEBI UPI mandate acceptance timing"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_126_37': 1},
 '"derivative instruments pit regulations"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_8_19': 1},
 '"Annexure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_2_10': 1},
 '"SEBI circular confirmation submission"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_33_0': 1},
 '"UPS information handling regulations"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_6_14': 1},
 '"unaudited financial statements subsidiaries"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_104_48': 1},
 '"credit payment modes"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_101_44': 1},
 '"financial results audit"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_115_0': 1},
 '"SEBI UPI block unblock complaints"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_34_3': 1},
 '"credit rating agency"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_42_24': 1},
 '"water consumption calculation formula"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_195_22': 1},
 '"stakeholder engagement environmental social topics"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_190_6': 1},
 '"freezing pan at security level"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_25_3': 1},
 '"SEBI regulations on share transfer"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_35_14': 1},
 '"Company financials outstanding debt"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_29_43': 1},
 '"Bid Revision Application Form"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_87_10': 1},
 '"Demerger and sale of units or divisions"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_214_17': 1},
 '"market intermediary rumors internal controls"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_4_10': 1},

# Start retriever

In [18]:
!pip install langchain-pinecone

Requirement already satisfied: langchain-pinecone in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (0.2.13)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.34 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (1.2.20)
Requirement already satisfied: pinecone<8.0.0,>=6.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (7.3.0)
Requirement already satisfied: numpy!=2.0.2,>=1.26.4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (2.3.1)
Requirement already satisfied: langchain-openai>=0.3.11 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (1.1.11)
Requirement already satisfied: httpx>=0.28.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (0.28.1)
Requirement already satisfied: simsimd>=5.9.11 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (6.5.16)
Requirement already satisfied: pydantic>=2.11.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (2.12.5)
Requirement already satisfied: anyio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (4.12.1)
Requirement already satisfied: certifi in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (1.0.9)
Requirement already satisfied: idna in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.28.0->langchain-pinecone) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (24.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.14.1)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-openai>=0.3.11->langchain-pinecone) (2.29.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-openai>=0.3.11->langchain-pinecone) (0.12.0)
Requirement already satisfied: pinecone-plugin-assistant<2.0.0,>=1.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.8.0)
Requirement already satisfied: pinecone-plugin-interface<0.0.8,>=0.0.7 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.0.7)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.0.post0)
Requirement already satisfied: urllib3>=1.26.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.3)
Requirement already satisfied: aiohttp>=3.9.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (3.13.3)
Requirement already satisfied: aiohttp-retry<3.0.0,>=2.9.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (0.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.23.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.25.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (0.13.0)
Requirement already satisfied: sniffio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (1.3.1)
Requirement already satisfied: tqdm>4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (4.67.3)
Requirement already satisfied: six>=1.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from python-dateutil>=2.5.3->pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.17.0)
Requirement already satisfied: regex>=2022.1.18 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai>=0.3.11->langchain-pinecone) (2026.2.28)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.4.6)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [19]:
import sys
sys.path.append('/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval')

from dotenv import load_dotenv
load_dotenv("/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/ingestion.env")

from Repositories.pinecone_repository import PineconeRepository

In [20]:
from Repositories.pinecone_repository import PineconeConfig
from src.sentence_transformer_embedding import SentenceTransformerEmbedding
from src.sparse_embedding import SentenceTransformerSparseEmbedding

In [21]:
config = PineconeConfig()

dense_embedding_strategy = SentenceTransformerEmbedding(config)

sparse_embedding_strategy = SentenceTransformerSparseEmbedding(config)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6448.34it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 204/204 [00:00<00:00, 40419.39it/s]
The tied weights mapping and config for this model specifies to tie bert.embeddings.word_embeddings.weight to cls.predictions.decoder.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
BertForMaskedLM LOAD REPORT from: naver/splade-cocondenser-ensembledistil
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [22]:
import os

In [23]:
pinecone_repository = PineconeRepository(
            api_key=os.getenv("PINECONE_API_KEY"),
            environment=os.getenv("PINECONE_ENVIRONMENT", "us-east-1-aws"),
            dense_embedding_strategy=dense_embedding_strategy,
            sparse_embedding_strategy=sparse_embedding_strategy,
            pinecone_config=config
        )

In [24]:
df_sampled["relevant_docs"] = df_sampled["query"].apply(pinecone_repository.query_vector_store_for_rankx)

In [25]:
df_sampled.to_csv("/Users/midhunln/Documents/rag20march_with_eval/notebooks/datasets/sentence_transformers/chunk_query_relevant_docs.csv", index = False)

In [26]:
df_sampled.head()

,id,text,query,relevant_docs
35,/Users/midhunln/Documents/rag20march_with_eval...,Page 15 of 132 \n \nChapter 5: Compensation to...,"""IPO allotment failure compensation""",[{'id': '/Users/midhunln/Documents/rag20march_...
268,/Users/midhunln/Documents/rag20march_with_eval...,Page 117 of 132,"""page 117""",[{'id': '/Users/midhunln/Documents/rag20march_...
643,/Users/midhunln/Documents/rag20march_with_eval...,"income recognition, asset classification, prov...","""chartered accountants report""",[{'id': '/Users/midhunln/Documents/rag20march_...
377,/Users/midhunln/Documents/rag20march_with_eval...,2026 – 27 Top 1000 listed entities \n \n3. ESG...,"""ESG disclosures value chain""",[{'id': '/Users/midhunln/Documents/rag20march_...
478,/Users/midhunln/Documents/rag20march_with_eval...,requirements which is not specified by SEBI un...,"""SEBI circular requirements""",[{'id': '/Users/midhunln/Documents/rag20march_...

In [27]:
df_sampled["relevant_docs"].iloc[0]

[{'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_14_35',
  'score': 21.7768345},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_32_44',
  'score': 19.8449631},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_14_36',
  'score': 16.3281155},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_52_42',
  'score': 16.1422958},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_15_38',
  'score': 15.6715603},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_34_1',
  'score': 15.4678755},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_31_43',
  'score': 14.0478897},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_122_28',
  'score': 11.9018373},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_99_38',
  'score': 11.4982071},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_32_45',
  'score': 10.874567}]

In [28]:
qrels_dict = {}

for i, row in df_sampled.iterrows():
    qid = str(i)
    true_doc = row["id"]   # single doc id string
    qrels_dict[qid] = {true_doc: 1}

In [29]:
run_dict = {}

for i, row in df_sampled.iterrows():
    qid = str(i)
    
    run_dict[qid] = {
        doc["id"]: float(doc["score"])
        for doc in row["relevant_docs"]
    }

In [30]:
from ranx import Qrels, Run, evaluate

qrels = Qrels(qrels_dict)
run = Run(run_dict)

metrics = [
    "mrr",
    "ndcg@10",
    "recall@5",
    "recall@10",
    "precision@5"
]

results = evaluate(qrels, run, metrics)
print(results)

{'mrr': np.float64(0.6078435578435578), 'ndcg@10': np.float64(0.66452595030322), 'recall@5': np.float64(0.8108108108108109), 'recall@10': np.float64(0.8378378378378378), 'precision@5': np.float64(0.16216216216216214)}

In [31]:
final_result = pd.Series(results)

In [32]:
final_result

mrr            0.607844
ndcg@10        0.664526
recall@5       0.810811
recall@10      0.837838
precision@5    0.162162
dtype: float64